import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navigation/nav-bar";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="w-full">
        <body className="w-full pt-10">{children}</body>
      </html>
    </ClerkProvider>
  );
}
