import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navigation/nav-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full">
      <body className="w-full">
        <main className="flex flex-col items-center justify-center">
          <NavBar />
          <div className="flex flex-col items-center justify-cente">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
